name: InvRestore
version: '1.0.2'
main: me.honeyberries.invRestore.InvRestore
api-version: 1.19
authors: [ HoneyBerries ]
description: A plugin that allows players to restore their inventory upon death using the /restore command.

commands:
  restore:
    description: Restores the inventory of the specified player or yourself.
    usage: /restore <death|save> [player]
    aliases: [invrestore, invres]
  invsave:
    description: Saves your current inventory
    usage: /invsave [player]
    aliases: [inventorysave, saveinv, saveinventory]
  invview:
    description: View a player's saved or death inventory.
    usage: /invview <player> <death|save>
    aliases: [invview, inventoryview, viewinv, viewinventory]

permissions:
  invrestore.restore:
    description: Allows the use of the /restore command to restore inventories.
    default: op
  invrestore.save:
    description: Allows you to save your inventory.
    default: true
  invrestore.view:
    description: Allows you to view the saved inventories of other players.
    default: op