name: InvRestore
version: '1.0.1'
main: me.honeyberries.invRestore.InvRestore
api-version: 1.19
authors: [ HoneyBerries ]
description: A plugin that allows players to restore their inventory upon death using the /restore command.

commands:
  restore:
    description: Restores the inventory of the specified player or yourself.
    usage: /restore [player]
    aliases: [res, invrestore, invres]
  invsave:
    description: Saves your current inventory
    usage: /invsave [player]
    aliases: [inventorysave, saveinv, saveinventory]

permissions:
  invrestore.restore:
    description: Allows the use of the /restore command to restore inventories.
    default: op
  invrestore.save:
    description: Allows you to save your inventory.
    default: true