name: InvRestore
version: '1.2.0'
main: me.honeyberries.invRestore.InvRestore
api-version: 1.21
authors: [ HoneyBerries ]
description: A plugin that allows players to save, view, and restore their inventories with ease.
folia-supported: true
commands:
  inventoryrestore:
    description: Restore a saved or last-death inventory for yourself or another player.
    usage: /inventoryrestore <death|save> [player]
    aliases: [restore, invrestore, invres]
  inventorysave:
    description: Save your current inventory or another player's inventory for later recovery.
    usage: /inventorysave [player]
    aliases: [invsave, saveinv]
  inventorysaveview:
    description: View a saved or death inventory for yourself or another player.
    usage: /inventorysaveview <death|save> [player]
    aliases: [invsaveview, viewsave]

permissions:
  invrestore.restore:
    description: Grants permission to restore inventories using the /restore command.
    default: op
  invrestore.save:
    description: Grants permission to save your own or another player's inventory.
    default: true
  invrestore.view:
    description: Grants permission to view saved or death inventories of other players.
    default: op
